name: Deploy Configuration

on:
  push:
    branches:
      - main
    paths:
      - 'config/database.rules.json'
      - 'config/firebase.json'
      - '.github/workflows/deploy.yml'

jobs:
  deploy-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy Database Rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: "trivia-night-e9193"
        run: firebase deploy --config config/firebase.json --only database --project $PROJECT_ID --token $FIREBASE_TOKEN
